### PR TITLE
Create README for LambdaLayer users

### PR DESCRIPTION
**Pull request by zdev24**
The helpful readme for users who use this library with lambda layer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zdev24** [comment]
[OnlyLambdaLayer-Node18-aws-jwt-verify.webm](https://github.com/awslabs/aws-jwt-verify/assets/9767894/77a8632c-bc59-428a-8423-05ae74db0eaf)

**Comment by zdev24** [comment]
[OnlyLambdaLayer-Node18-aws-jwt-verify2.webm](https://github.com/awslabs/aws-jwt-verify/assets/9767894/a1e9ad6b-6eb7-471c-8109-fddd27c34397)

**Comment by ottokruse** [comment]
Hi mate. Sorry for not having come back to this earlier.

I'm not sure about this PR if I'm honest:

- I think these instructions are general AWS Lambda layer instructions, not per se particular to this lib. e.g. you can use this lib in CommonJS mode too, doesn't have to be "module" (ESM) per se.
- Node 16 should work too (and even 14 still even though that's end of life)

All in all there is nothing particular about this library with regards to Lambda layers. (If there is, that would be a bug)

Maybe instead of a PR you can file an issue and resolve it immediately with the answer. That way people with a similar problem will b able to find your solution.

**Comment by ottokruse** [comment]
If you feel differently let us know and we can discuss.

Thank you for your effort anyway!

**Pull request closed without merging**
