### PR TITLE
Allow "aud" claim to be an array of strings

### PR DESCRIPTION
**Pull request by garretcharp**

### CODE REVIEW

**Comment by ottokruse** [comment]
Thanks!

Can you add a unit test for this also?

And run prettier please (`npm run prettier`).

(You can check if all is okay, prettier/linting/tests/etc, by running `npm run test:all`, we run that as part of publishing too)

**Comment by garretcharp** [comment]
Great, just added in the requested changes

**Comment by ottokruse** [comment]
Thanks for the (speedy) contribution
We'll release a new version to NPM soon.

**Comment by ottokruse** [comment]
Just published!

https://github.com/awslabs/aws-jwt-verify/releases/tag/v1.0.2

Let us know your feedback please.

**Pull request merged**
